import { Product } from "./store-context";

export const products: Product[] = [
  {
    id: 1,
    name: 'MacBook Pro 16" M3 Max',
    price: 209900,
    originalPrice: 234900,
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80",
      "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=800&q=80",
      "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&q=80",
      "https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=800&q=80",
    ],
    category: "Laptops",
    rating: 4.9,
    reviews: 2341,
    badge: "Best Seller",
    description: "The most powerful MacBook Pro ever with M3 Max chip. Up to 128GB unified memory and 8TB storage.",
    features: [
      "M3 Max chip with 16-core CPU and 40-core GPU",
      "Up to 128GB unified memory",
      "16.2-inch Liquid Retina XDR display",
      "Up to 22 hours battery life",
      "1080p FaceTime HD camera",
      "Six-speaker sound system with spatial audio",
    ],
    variants: [
      { type: "Storage", options: ["512GB", "1TB", "2TB", "4TB"] },
      { type: "Color", options: ["Space Black", "Silver"] },
    ],
    inStock: true,
    customerReviews: [
      { name: "Rahul Sharma", rating: 5, comment: "Absolutely incredible performance. Handles everything I throw at it.", date: "2 weeks ago" },
      { name: "Priya Singh", rating: 5, comment: "Best laptop I've ever owned. The display is stunning.", date: "1 month ago" },
      { name: "Amit Patel", rating: 4, comment: "Great machine but runs warm under heavy load.", date: "2 months ago" },
    ],
  },
  {
    id: 2,
    name: "Sony WH-1000XM5 Headphones",
    price: 29990,
    originalPrice: 34990,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80",
      "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&q=80",
      "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&q=80",
    ],
    category: "Audio",
    rating: 4.8,
    reviews: 5672,
    badge: "Top Rated",
    description: "Industry-leading noise cancellation with exceptional sound quality and 30-hour battery life.",
    features: [
      "Industry-leading noise cancellation",
      "30-hour battery life",
      "Crystal clear hands-free calling",
      "Multipoint connection",
      "Speak-to-chat technology",
      "Lightweight 250g design",
    ],
    variants: [
      { type: "Color", options: ["Black", "Silver", "Midnight Blue"] },
    ],
    inStock: true,
    customerReviews: [
      { name: "Sneha Gupta", rating: 5, comment: "Excellent noise cancellation. Perfect for flights.", date: "1 week ago" },
      { name: "Vikram Reddy", rating: 5, comment: "Battery lasts forever. Sound quality is top notch.", date: "3 weeks ago" },
      { name: "Ananya Joshi", rating: 4, comment: "Comfortable for long sessions. ANC is the best.", date: "1 month ago" },
    ],
  },
  {
    id: 3,
    name: "iPhone 15 Pro Max 256GB",
    price: 159900,
    image: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&q=80",
      "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=800&q=80",
      "https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=800&q=80",
    ],
    category: "Smartphones",
    rating: 4.7,
    reviews: 8923,
    description: "Titanium design. A17 Pro chip. 48MP camera system with 5x optical zoom.",
    features: [
      "A17 Pro chip — the fastest ever",
      "48MP main camera with 5x optical zoom",
      "Titanium design, lightest Pro ever",
      "Action button for instant access",
      "USB-C with USB 3 speeds",
      "All-day battery life",
    ],
    variants: [
      { type: "Storage", options: ["256GB", "512GB", "1TB"] },
      { type: "Color", options: ["Natural Titanium", "Blue", "White", "Black"] },
    ],
    inStock: true,
    customerReviews: [
      { name: "Karan Mehta", rating: 5, comment: "Camera is incredible. Best phone I've used.", date: "5 days ago" },
      { name: "Deepika Nair", rating: 4, comment: "Smooth performance, great display. Pricey though.", date: "2 weeks ago" },
    ],
  },
  {
    id: 4,
    name: 'Samsung 65" OLED 4K Smart TV',
    price: 149990,
    originalPrice: 184990,
    image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&q=80",
      "https://images.unsplash.com/photo-1461151304267-38535e780c79?w=800&q=80",
    ],
    category: "TVs",
    rating: 4.6,
    reviews: 1456,
    badge: "Sale",
    description: "Stunning OLED display with infinite contrast and vivid colors. Dolby Atmos and 120Hz refresh rate.",
    features: [
      "4K OLED with infinite contrast",
      "120Hz refresh rate for smooth motion",
      "Dolby Atmos & Dolby Vision",
      "Smart TV with built-in apps",
      "Gaming Hub with cloud gaming",
      "Slim One Connect design",
    ],
    variants: [
      { type: "Size", options: ['55"', '65"', '77"'] },
    ],
    inStock: true,
    customerReviews: [
      { name: "Suresh Kumar", rating: 5, comment: "Picture quality is absolutely stunning. Worth every rupee.", date: "1 month ago" },
      { name: "Meera Iyer", rating: 4, comment: "Great TV for movies and gaming. Setup was easy.", date: "2 months ago" },
    ],
  },
  {
    id: 5,
    name: "iPad Air M2 11-inch",
    price: 49900,
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&q=80",
      "https://images.unsplash.com/photo-1585790050230-5dd28404ccb9?w=800&q=80",
    ],
    category: "Tablets",
    rating: 4.8,
    reviews: 3210,
    description: "Supercharged by M2. Stunningly thin and light with 10-hour battery.",
    features: [
      "M2 chip for next-level performance",
      "11-inch Liquid Retina display",
      "12MP front and back cameras",
      "All-day battery life",
      "Apple Pencil & Magic Keyboard support",
      "Wi-Fi 6E support",
    ],
    variants: [
      { type: "Storage", options: ["128GB", "256GB", "512GB", "1TB"] },
      { type: "Color", options: ["Space Grey", "Blue", "Purple", "Starlight"] },
    ],
    inStock: true,
    customerReviews: [
      { name: "Rohan Das", rating: 5, comment: "Perfect for students and artists. Love the Apple Pencil support.", date: "3 weeks ago" },
    ],
  },
  {
    id: 6,
    name: "Logitech MX Master 3S Mouse",
    price: 8495,
    originalPrice: 10995,
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&q=80",
      "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&q=80",
    ],
    category: "Accessories",
    rating: 4.7,
    reviews: 4521,
    description: "Precision tracking on any surface. Quiet clicks. Ergonomic design.",
    features: [
      "8K DPI tracking on any surface",
      "Quiet clicks — 90% noise reduction",
      "USB-C quick charging",
      "Connect up to 3 devices",
      "Ergonomic sculpted shape",
      "70 days battery on full charge",
    ],
    variants: [
      { type: "Color", options: ["Graphite", "Pale Grey"] },
    ],
    inStock: true,
    customerReviews: [
      { name: "Arjun Verma", rating: 5, comment: "Best mouse I've ever used. So comfortable.", date: "1 week ago" },
      { name: "Neha Saxena", rating: 4, comment: "Quiet clicks are a game changer in office.", date: "1 month ago" },
    ],
  },
  {
    id: 7,
    name: "Apple Watch Ultra 2",
    price: 89900,
    image: "https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=800&q=80",
      "https://images.unsplash.com/photo-1546868871-af0de0ae72be?w=800&q=80",
    ],
    category: "Wearables",
    rating: 4.8,
    reviews: 1876,
    badge: "New",
    description: "The most rugged and capable Apple Watch. Built for extreme adventures.",
    features: [
      "49mm titanium case",
      "Brightest Apple Watch display ever",
      "Precision dual-frequency GPS",
      "Up to 36 hours battery life",
      "Water resistant to 100m",
      "Advanced health sensors",
    ],
    variants: [
      { type: "Band", options: ["Alpine Loop", "Trail Loop", "Ocean Band"] },
      { type: "Color", options: ["Orange", "Blue", "Green", "Black"] },
    ],
    inStock: true,
    customerReviews: [
      { name: "Ravi Shankar", rating: 5, comment: "Perfect for trekking. Battery lasts the whole trip.", date: "2 weeks ago" },
    ],
  },
  {
    id: 8,
    name: "Sony PlayStation 5 Slim",
    price: 49990,
    image: "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800&q=80",
      "https://images.unsplash.com/photo-1607853202273-797f1c22a38e?w=800&q=80",
    ],
    category: "Gaming",
    rating: 4.9,
    reviews: 12340,
    badge: "Popular",
    description: "Experience lightning-fast loading and stunning 4K graphics with ray tracing.",
    features: [
      "Custom AMD Zen 2 processor",
      "4K gaming at up to 120fps",
      "Ray tracing for realistic graphics",
      "Ultra-high speed SSD",
      "3D Audio technology",
      "Backward compatible with PS4 games",
    ],
    variants: [
      { type: "Edition", options: ["Digital", "Disc"] },
    ],
    inStock: true,
    customerReviews: [
      { name: "Aditya Chopra", rating: 5, comment: "Mind-blowing graphics. Loading times are insane.", date: "3 days ago" },
      { name: "Pooja Desai", rating: 5, comment: "Best gaming console ever. The controller feels amazing.", date: "2 weeks ago" },
      { name: "Sanjay Mishra", rating: 4, comment: "Great console. Wish there were more exclusives.", date: "1 month ago" },
    ],
  },
];

export const categories = ["All", "Laptops", "Smartphones", "Audio", "TVs", "Tablets", "Accessories", "Wearables", "Gaming"];
